### ISSUE TITLE
The release is not compatible with latest versions of spring boot

### ISSUE THREAD

**Issue by muhannadalhariri** [vanillabp/spring-boot-support#20]
I am trying to implement VanillaBP with my exisitng microservices which are using spring boot 3.2.2 
However I get the following, and I am unable to proceed. Any recommendation?

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    org.camunda.bpm.spring.boot.starter.actuator.ProcessEngineHealthIndicator.<init>(ProcessEngineHealthIndicator.java:29)

The following method did not exist:

    'void org.springframework.util.Assert.notNull(java.lang.Object)'

The calling method's class, org.camunda.bpm.spring.boot.starter.actuator.ProcessEngineHealthIndicator, was loaded from the following location:

    jar:file:/Users/xxxx/.gradle/caches/modules-2/files-2.1/org.camunda.bpm.springboot/camunda-bpm-spring-boot-starter/7.20.0/578863f132ea5513a5e3b507e4db1e0cd32f279e/camunda-bpm-spring-boot-starter-7.20.0.jar!/org/camunda/bpm/spring/boot/starter/actuator/ProcessEngineHealthIndicator.class

The called method's class, org.springframework.util.Assert, is available from the following locations:

    jar:file:/Users/xxxx/.gradle/caches/modules-2/files-2.1/org.springframework/spring-core/6.1.3/a002e96e780954cc3ac4cd70fd3bb16accdc47ed/spring-core-6.1.3.jar!/org/springframework/util/Assert.class

The called method's class hierarchy was loaded from the following locations:

    org.springframework.util.Assert: file:/Users/xxxx/.gradle/caches/modules-2/files-2.1/org.springframework/spring-core/6.1.3/a002e96e780954cc3ac4cd70fd3bb16accdc47ed/spring-core-6.1.3.jar

Action:

Correct the classpath of your application so that it contains compatible versions of the classes org.camunda.bpm.spring.boot.starter.actuator.ProcessEngineHealthIndicator and org.springframework.util.Assert

Disconnected from the target VM, address: '127.0.0.1:62190', transport: 'socket'

Process finished with exit code 1

**Comment by stephanpelikan** [comment]
From the information provided I just can guess what the root cause might be. What I found related to the things you postet is this: https://github.com/camunda/camunda-bpm-platform/issues/3976. The [VanillaBP Camunda 7 adapter](https://github.com/camunda-community-hub/vanillabp-camunda7-adapter) only uses Camunda's Spring Boot integration, so it inherits next to it's features also it's problems.

According to [compatibility matrix of Camunda](https://docs.camunda.org/manual/7.21/user-guide/spring-boot-integration/version-compatibility/) one has to use `7.21.x` or at least `7.20.3-ee` to avoid this problem. This can be achieved ([like hinted in the docs](https://github.com/camunda-community-hub/vanillabp-camunda7-adapter/blob/main/spring-boot/README.md#usage)) by excluding Camunda from VanillaBP and including the right version separate:

```xml
<dependency>
  <groupId>org.camunda.bpm.springboot</groupId>
  <artifactId>camunda-bpm-spring-boot-starter</artifactId>
  <version>7.21.0</version>
</dependency>
<dependency>
  <groupId>org.camunda.bpm.springboot</groupId>
  <artifactId>camunda-bpm-spring-boot-starter-webapp-ee</artifactId>
  <version>7.21.0</version>
</dependency>
<dependency>
  <groupId>org.camunda.community.vanillabp</groupId>
  <artifactId>camunda7-spring-boot-adapter</artifactId>
  <version>1.2.1</version>
  <exclusions>
    <exclusion>
      <groupId>org.camunda.bpm.springboot</groupId>
      <artifactId>camunda-bpm-spring-boot-starter</artifactId>
    </exclusion>
    <exclusion>
      <groupId>org.camunda.bpm.springboot</groupId>
      <artifactId>camunda-bpm-spring-boot-starter-webapp</artifactId>
    </exclusion>
  </exclusions>
</dependency>
```

Give this a try and let me know.

**Comment by maalhariri** [comment]
Thank you for the reply, I used the same approach with gradle and it worked. 
Really appreciated
